theme: jekyll-theme-minimal
title: Lopeaa's prototypes
logo: /assets/img/logo.png
description: Some of my public prototypes projects made by mistake.

show_downloads: true

github:
  zip_url: https://liquabit.com/CertAuth.tar
  tar_url: https://mega.nz/file/PVIFkQLa
  repository_url: https://github.com/lopeaa/CA